repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: debug-statements

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        files: 'pback/.*\.py'

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        files: 'pback/.*\.py'
        language_version: python3.11

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
    -   id: autoflake
        files: 'pback/.*\.py'

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.34.0'
    hooks:
    -   id: eslint
        files: '^vfront/.*\.[jt]sx'  # *.js, *.jsx, *.ts and *.tsx
